<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    '46bf1fdf74afcb5cc9d45395436ee24c' => $vendorDir . '/widmogrod/php-functional/src/Functional/functions.php',
    '8cdc1725b6247a1cc84c9911b0fcbebc' => $vendorDir . '/widmogrod/php-functional/src/Functional/predicates.php',
    'e070b0f8d1547098ec6a4253c6affddd' => $vendorDir . '/widmogrod/php-functional/src/Functional/strings.php',
    '4d86776776ff74ccf65cca67a5df7059' => $vendorDir . '/widmogrod/php-functional/src/Monad/Either/functions.php',
    'be49bae08a3e58892601a353e9043baf' => $vendorDir . '/widmogrod/php-functional/src/Monad/Maybe/functions.php',
    'a661e6a3d799b70d860e35339daaa92d' => $vendorDir . '/widmogrod/php-functional/src/Monad/IO/functions.php',
    '09eaa491d0fd74f6a1379a1deb95e72b' => $vendorDir . '/widmogrod/php-functional/src/Monad/IO/errors.php',
    '1ad0c1c1d771481281a7dc68e7438606' => $vendorDir . '/widmogrod/php-functional/src/Monad/State/functions.php',
    '14befb123c1130ec9db69bcc4e1c46f4' => $vendorDir . '/widmogrod/php-functional/src/Monad/Control/functions.php',
);
