<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5162e4e2b9f1983a36d2fc1ca9e3f3cf
{
    public static $prefixesPsr0 = array (
        'v' => 
        array (
            'vektah\\parser_combinator' => 
            array (
                0 => __DIR__ . '/..' . '/vektah/parser-combinator/src/main',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit5162e4e2b9f1983a36d2fc1ca9e3f3cf::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
